apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app: my-web-app
spec:
  selector:
    matchLabels:
      project: learn-k8s
  template:
    metadata:
      labels:
        project: learn-k8s
    spec:
      containers:
        - name: my-app
          image: app:0.0.1
          ports:
            - containerPort: 8080