apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-autoscaling
  labels:
    app: my-web-app
    env: local
    owner: TheForest
    tier: backend
spec:
  #  replicas: 2   # Don't need this anymore as we are using HorizontalPodAutoscaler
  selector:
    matchLabels:
      project: red-k8s
  template:
    metadata:
      labels:
        project: red-k8s
    spec:
      containers:
        - name: red-k8s-app
          image: app:0.0.1
          ports:
            - containerPort: 8080

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-web-deployment-autoscaling
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
