apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-replicas
  labels:
    app: my-web-app
    env: local
    owner: TheForest
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      project: l-k8s
  template:
    metadata:
      labels:
        project: l-k8s
    spec:
      containers:
        - name: l-k8s-app
          image: app:0.0.1
          ports:
            - containerPort: 8080